# Generated by Django 5.1.6 on 2025-03-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AlterUniqueTogether(
            name='courseparticipant',
            unique_together={('student', 'course', 'role')},
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='courseparticipant',
            unique_together={('staff', 'course', 'role'), ('student', 'course', 'role')},
        ),
    ]
